image: ubuntu:latest

stages:
  - build

before_script:
  - echo "Before script install this on ubuntu image "
  - apt-get update && apt-get -y install clang

build_job:
  stage: build
  only:
    - main
  script:
    - mkdir build
    - clang -Wall -Wextra -Werror -O3 -Iinclude/ src/main.c -o build/temlang -lm -march=native -fno-math-errno
    - chmod -R 777 *
    - pwd

  artifacts:
    expire_in: 265 days
    paths:
      [build]
